services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
  db:
    image: postgres:15.13-alpine3.21
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
  redis:
    image: redis:7.2.8-alpine3.21
    ports:
      - "6379:6379"
    restart: unless-stopped