services:
  app:
    build: .
#    ports:
#      - "3000:3000"
    restart: unless-stopped
    volumes:
      - app_data:/opt/app/storage
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
  db:
    image: postgres:15.13-alpine3.21
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2.8-alpine3.21
#    ports:
#      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
  app_data: