services:
  app:
    image: registry.digitalocean.com/ikromov-devops-registry/my-node-app:1.0.1
    # build: .
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_HOST: localhost
      REDIS_PORT: 6379  
  db:
    image: postgres:15.13-alpine3.21
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.8-alpine3.21
    # ports:
    #   - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
